### Admin qo'shish
POST http://localhost:3000/admins
Authorization: 
Content-Type: application/json

{
  "full_name": "",
  "username": "",
  "password": ""
}


### Login qilish
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "",
  "password": ""
}


### Adminlar ro'yxati
GET http://localhost:3000/admins
Authorization: 


### Bitta adminni ko'rish
GET http://localhost:3000/admins/:id
Authorization: 


### Edit admin (all)
PATCH http://localhost:3000/admins
Authorization: 
Content-Type: application/json

{
  "full_name": "",
  "username": "",
  "password": ""
}


### Edit admin (only super_admin)
PATCH http://localhost:3000/admins/:id
Authorization: 
Content-Type: application/json

{
  "full_name": "",
  "username": "",
  "password": ""
}


### Adminni o'chirish (only super_admin)
DELETE http://localhost:3000/admins/:id
Authorization: