### Muallif qo'shish
POST http://localhost:3000/authors
Authorization: 
Content-Type: application/json

{
  "full_name": ""
}


### Mualliflar ro'yxati
GET http://localhost:3000/authors
Authorization: 


### Bitta muallif
GET http://localhost:3000/authors/:id
Authorization: 


### Muallifnini tahrirlash
PATCH http://localhost:3000/authors/:id
Authorization: 
Content-Type: application/json

{
  "full_name": ""
}


### Muallifni o'chirish
DELETE http://localhost:3000/authors/:id
Authorization: 