### Kitob qo'shish
POST http://localhost:3000/books
Authorization:
Content-Type: application/json

{
  "title": "",
  "publisher": "",
  "author": "",
  "copies": 
}


### Kitoblar ro'yxati
GET http://localhost:3000/books
Authorization:


### Bitta kitob
GET http://localhost:3000/books/:id
Authorization:


### Kitobni tahrirlash
PATCH http://localhost:3000/books/:id
Authorization:
Content-Type: application/json

{
  "title": "",
  "publisher": "",
  "author": "",
  "copies": 
}


### Kitobni o'chirish
DELETE http://localhost:3000/books/:id
Authorization: