### Kitobxon qo'shish
POST http://localhost:3000/borrowers
Authorization:
Content-Type: application/json

{
  "full_name": "",
  "address": "",
  "phone": "+9989"
}


### Kitobxonlar ro'yxati
GET http://localhost:3000/borrowers
Authorization: 


### Bitta kitobxon
GET http://localhost:3000/borrowers/:id
Authorization: 


### Kitobxonni tahrirlash
PATCH http://localhost:3000/borrowers/:id
Authorization:
Content-Type: application/json

{
  "full_name": "",
  "address": "",
  "phone": "+9989"
}


### Kitobxoni o'chirish
DELETE http://localhost:3000/borrowers/:id
Authorization: