### Buyurtma yaratish
POST http://localhost:3000/loans
Authorization:
Content-Type: application/json

{
  "book": "",
  "borrower": "",
  "due_date": ""
}


### Buyurtmalarni ko'rish
GET http://localhost:3000/loans
Authorization:


### Bitta buyurtmani ko'rish
GET http://localhost:3000/loans/:id
Authorization:


### Kitob qaytarilganini qayd qilish
PATCH http://localhost:3000/loans/:id
Authorization: